name: Release

on:
  workflow_dispatch: # manual trigger


permissions:
  contents: 'write'
  id-token: 'write' # for WIF auth

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      - name: Re-configure AWS credentials for S3 access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::565393054667:role/code-artifact-access-to-eli-jordan-gh-org
          aws-region: us-west-2

      - name: Publish sbt project
        run: |
          export CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token \
            --domain eli-test \
            --domain-owner 565393054667 \
            --region us-west-2 \
            --query authorizationToken --output text)"

          sbt 'lib/publish'
